# Installing required ruby versions
- include: ruby-install.yml ruby_version={{ version }}
  sudo: yes
  sudo_user: "{{ deploy_user }}"

# Common ruby environment tasks (e.g. adding a .gemrc, ...)
- include: common-post.yml
  sudo: yes
  sudo_user: "{{ deploy_user }}"

